<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>Capa_Datos</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="26.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Capa Entidad\CapaEntidad.csproj" />
  </ItemGroup>

</Project>
