<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>Capa_Negocio</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Capa Datos\CapaDatos.csproj" />
    <ProjectReference Include="..\Capa Entidad\CapaEntidad.csproj" />
  </ItemGroup>

</Project>
